version: '3.8'

services:
  postgres:
    image: postgres:15
    platform: linux/arm64/v8
    container_name: shubham_autovacuum
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_tune_autovacuum
    ports:
      - "5433:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
      - ./custom_config/postgresql.conf:/etc/postgresql/postgresql.conf
      - pg_logs:/var/log/postgresql
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    platform: linux/arm64/v8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    platform: linux/arm64/v8
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    restart: always

  grafana:
    image: grafana/grafana:latest
    platform: linux/arm64/v8
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    depends_on:
      - prometheus
    restart: always

  postgres_exporter:
    image: quay.io/prometheuscommunity/postgres-exporter
    platform: linux/arm64/v8
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/db_tune_autovacuum?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      - postgres
    restart: always

  pgbadger:
    image: alpine:latest
    container_name: pgbadger
    platform: linux/arm64/v8
    depends_on:
      - postgres
    volumes:
      - pg_logs:/var/log/postgresql
      - ./pgbadger_reports:/var/www/html
    entrypoint: >
      sh -c "
      apk add --no-cache perl perl-utils nginx curl && 
      curl -L https://github.com/darold/pgbadger/archive/master.tar.gz | tar xz && 
      cd pgbadger-master && 
      perl pgbadger -f stderr -o /var/www/html/index.html /var/log/postgresql/postgresql.log && 
      while true; do sleep 3600; perl pgbadger -f stderr -o /var/www/html/index.html /var/log/postgresql/postgresql.log; done &
      nginx -g 'daemon off;'
      "
    ports:
      - "8080:80"

volumes:
  pg_data:
  prometheus_data:
  pg_logs:

